import { createSlice } from '@reduxjs/toolkit';

// Create a slice for authentication
const authSlice = createSlice({
  name: 'auth',
  initialState: {
    isLoggedIn: false, // Initial login status
    userId: null, // Initial user ID
  },
  reducers: {
    // Reducer to handle login action
    login(state, action) {
      state.isLoggedIn = true;
      state.userId = action.payload.userId;
    },
    // Reducer to handle logout action
    logout(state) {
      state.isLoggedIn = false;
      state.userId = null;
    },
  },
});

// Export the actions generated by createSlice
export const { login, logout } = authSlice.actions;
// Export the reducer to be used in the store
export default authSlice.reducer;
